### ISSUE TITLE
Pay'n'Spray bug.

### ISSUE THREAD

**Issue by DrakeakaRaymond** [pnshr/SOLSRP#281]
There's a bug in the pay'n'spray, which is the very far edge of the pay'n'spray, when you with high speed, or a non stop slow speed to the edge of the garage, the edge when you keep driving straight you hit on it, that wall, and keep driving then stop with clicking SPACE, it repairs your car without you paying money, so that's it, and I hope you fix it.

**Comment by pnshr** [comment]
Which garage are you refering to? Idlewood? @DrakeakaRaymond

**Comment by DrakeakaRaymond** [comment]
Idlewood pay 'n' spray, yes. @pnshr
