### ISSUE TITLE
Double Hours Perk stops working after first paycheck

### ISSUE THREAD

**Issue by OGBiggie** [pnshr/SOLSRP#308]
Activated dh, got my paycheck, still works pretty cool, but then at the next paycheck the dh text dissapears and my played hours dont double

**Comment by pnshr** [comment]
@OGBiggie The minutes are doubling themselves, not the hours, for example if you have played 40 minutes from paycheck to paycheck, these minutes will be multiplied x 2 and therefore receive 80 minutes which is hour and 20 minutes - this will be listed as 1 hour in your stats and you'll need to play 40 minutes more to make them appear as 2. Test it again to confirm and let me know.
