### ISSUE TITLE
Gun run

### ISSUE THREAD

**Issue by RespiLSB** [pnshr/SOLSRP#315]
During gun run if you receive a mechanic call (or any call that places a checkpoint) removes a checkpoint from the gun run and doesn't re-appear.

**Comment by pnshr** [comment]
- [ ] Test

**Comment by pnshr** [comment]
+ Checkpoints shouldn't be shown when working, the job IDs could be resetting.

**Comment by pnshr** [comment]
+ Added /myjobid for debug usage if the bug occurs again.
