### ISSUE TITLE
Couple of useful scripts.

### ISSUE THREAD

**Issue by RespiLSB** [pnshr/SOLSRP#375]
/status
- No it is not viewing statistics, status command is a permanent /ame cloud above your head in a different color. For example /status Respi is limping due to a bullet in his leg or /status Respi would have a lap top on his lap. 

/dgun 
- When we drop a gun, we don't simply leave it on the ground, sometimes it's puncturing through the ground and whatnot. What I suggest is after you drop a gun you're holding, it gives you an ability to place it like an object, if possible have limit range. So you can put it leaning against the wall or strap on a rack.

/vcao
- Allow people not only to have attached object editor on their model, but also an attached object editor to a vehicle to have a unique design. 

/equip (/e)
- For quiet a while, I said we need a script that allows you to equip weapons instead of scrolling. They can also do it in a car. 

Increase Night Stick damage
- LSPD nightstick should be able to deal a lot of damage in one hit, realistically it's made out of hard steel enough to break a leg in a relaxed swing.

Furniture system
- I've noticed it definitely needs fair improvements. First, make every item $200/400 price and if sold, sell it for the same price as bought. If I accidentally press on an item, that costs $900, I sell it for $54? also we have limited objects so I suggest make it /hfurnish [Object id] and give it the ability to select a texture of any kind.

**Comment by andreiwow2** [comment]
Suggestion: Big weapons and melees should be visible on the body when scrolled, probably allow the player to adjust their location.

For example, bats, rifles etc.

Commands could be /holster edit and then the weapon he has on him.

@pnshr
