### ISSUE TITLE
Complete the migration, recover databases and server files

### ISSUE THREAD

**Issue by pnshr** [pnshr/SOLSRP#437]
**`Virtual Server To-Do List`**
- [x] Purchase a new private server, SSD powered. (KVM virtualization - Linux/Windows)
- [x] Install LAMP (Linux, Apache, MySQL and PHP).
- [x] Ensure the databases are local, not remote for better performance and security.
- [x] Install a control panel for the private server.
- [x] Set up new DNS settings, configure CloudFlare.
- [x] Configure web settings in the control panel.
- [x] Install the Comodo SSL (Secure Socket Layer).
- [x] Purchase and configure automatic daily backups of all databases.

**`Web/Forums To-Do List`**
- [x] Recover the web landing page and redirect pages.
- [x] Recover the forums and its database.
- [x] Configure the forums to work with the new database credentials.
- [x] Install memcached and other caching mechanisms.
- [x] Rebuild forum caches, incl. statistics, post counts etc.
- [x] Remove old threads, categories and update the forums look.
- [x] Reset usergroups and clear the unused ones.
- [x] Upload missing category images to the FTP. (+star_ico.png)
- [x] Fix issues with unicode symbols, probably MySQL charset causing it.
- [x] Remove old entries from the forum navigation.
- [x] Update missing PayPal images located on the old forums.
- [x] Update caterogies and forums information.
- [x] Add missing winter, black days, jumpsquad and awards winner ranks.
- [x] Reorder the ranks and their display priority.
- [x] Configure a proper SMTP server for the mail.
- [x] Install an e-mail system to send automated emails.
- [x] Recover the missing HTACCESS files for all pages.
- [x] Ensure supporters can change their custom user title even if they have another group set.
- [x] Add badges/medals and remove trophies.
- [x] Enable email confirmations and make sure people can reset their passwords.
- [x] Set-up a welcome message after user registration.
- [x] Remove obsolete forum user-groups.
- [x] Add missing pop-out and static notices.
- [x] Update the server changelogs.
- [x] Install imagemagick so GIF avatars work for donators.
- [x] Make the forum accessible at forum.sols-rpg.com address.

**`MySQL / DB Related`**
- [x] PLAYERS
- [x] VEHICLES
- [x] HOUSES
- [x] ATMS
- [x] ASSETS
- [x] FURNITURE
- [x] FUELSTATIONS
- [x] DEALERSHIPS
- [x] DOORS
- [x] ACHIEVEMENTS
- [x] BUGS

**`Game Server To-Do List`**
- [x] Recover the server and its database.
- [x] Configure DNS settings for server.sols-rpg.com:7777.
- [x] Recover server scriptfiles, AOE projects and logs.
- [x] Install latest server plugins and includes, including lates MySQL plugin & core.
- [x] Update the server database login credentials to establish connection.
- [x] Update file permissions so samp03svr, samp-npc and announce executables can be run.
- [x] Install 32-bit libraries and other dependencies.
- [x] Upload all custom-made player skins.
- [x] Ensure no firewall is blocking server ports.
- [x] Remove obsolete DNS settings from CloudFlare.
- [x] Move to 0.3.DL SA-MP version.
- [x] Ensure the hosted tab is functional and appearing on game-mp.

**`Post-recovery Processes`**
- [x] Add the table placeholders for houses.
- [x] Add the missing variables that were recently added to the tables.
- [x] Investigate for bugs and knock them off the surface (incl. MySQL error logs).
- [x] Fix issues with assets not being saved due to small string sizes.
- [x] Recover all fuel stations.
- [x] Recover all dealerships.
- [x] Recover all ATMs.
- [x] Recover all faction & personal (business) assets.
- [x] Ensure houses outside VW and INT are properly loaded and saved.
- [x] Add /createhouse [type] feature for seamless creation of houses.
- [x] Add facing angle support for houses when /exit-ing.
- [x] Do not show house labels and disallow /enter-ing when houses are in different VW/INT.
- [x] Recover all houses around LS and the countryside.
- [x] Fix custom models/skins showing up as invalid.
- [x] Recover all dynamic doors.
**>** 24/7 Stores - **Done**
**>** Gyms - **Done**
**>** Fast Food - **Done**
**>** Bank - **Done**
**>** Ammu-Nations  - **Done**
**>** Police Department  - **Done**
**>** Los Santos Prison  - **Done**
**>** Tattoo Parlors  - **Done**
**>** Barber Salons  - **Done**
**>** Sex Shops  - **Done**
**>** Jewelry Storess  - **Done**
**>** Bars  - **Done**
**>** Clubs  - **Done**
**>** Clothing Stores  - **Done**
**>** Restaurants  - **Done**
**>** Single Player Interiors  - **Done**
**>** Player-owned Interiors  - **Done**
- [x] Investigate why player stats don't get saved properly sometimes. (invalid connection handle '1')
- [x] Refund players In-Game.
- [x] Refund players on forums.
- [x] Fix issues related to GPCI and ClientIDs.

**Comment by IcezDonut** [comment]
Custom skins need to get fixed

**Comment by RafikEP** [comment]
^

Think it will be added after this

**Comment by pnshr** [comment]
Loading/Saving now works properly, MySQL errors have been fixed.
![sa-mp-082](https://user-images.githubusercontent.com/28692473/37117184-29405252-2259-11e8-9d2a-b26cce81afe8.png)

**Comment by pnshr** [comment]
Dealerships, fuel stations, assets and ATMs have been recovered.
More updates coming soon...
